name: learn-github-actions

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  check-bats-version:
    runs-on: ubuntu-latest
    steps:
      - name: execute echo command
        run: echo "this is a pen."
      - name: execute checkout
        uses: actions/checkout@v3
      - name: execute ls
        run: |
          ls -al
          cd .github/workflows/
          ls -al
